from __future__ import annotations

from io import BytesIO
from typing import Dict

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from components.db import create_invoice, fetch_patients, get_invoice, list_recent_invoices
from components.ui import format_currency


def _invoice_preview_html(invoice: Dict[str, str], hospital_name: str) -> str:
    return f"""
    <div class="invoice-paper">
        <div class="invoice-header">
            <div>
                <h3>SIMS Hospital Cloud</h3>
                <p>{hospital_name}</p>
            </div>
            <div class="invoice-meta">
                <strong>Invoice #{invoice['invoice_number']}</strong><br/>
                Issued: {invoice['issued_on']}<br/>
                Due: {invoice['due_date']}
            </div>
        </div>
        <hr/>
        <p><strong>Patient:</strong> {invoice['patient_name']}</p>
        <p><strong>Phone:</strong> {invoice['patient_phone']}</p>
        <p><strong>Address:</strong> {invoice['patient_address']}</p>
        <p><strong>Diagnosis:</strong> {invoice['patient_diagnosis']}</p>
        <p><strong>Doctor Assigned:</strong> {invoice['patient_doctor']}</p>
        <table class="invoice-table">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Status</th>
                    <th style="text-align:right;">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Clinical Services and Consultation</td>
                    <td>{invoice['status']}</td>
                    <td style="text-align:right;">{format_currency(float(invoice['amount']))}</td>
                </tr>
            </tbody>
        </table>
        <div class="invoice-total">Total: {format_currency(float(invoice['amount']))}</div>
    </div>
    """


def _build_invoice_pdf(invoice: Dict[str, str], hospital_name: str) -> bytes:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(45, height - 55, "SIMS Hospital Cloud")
    pdf.setFont("Helvetica", 11)
    pdf.drawString(45, height - 74, hospital_name)

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawRightString(width - 45, height - 55, f"Invoice {invoice['invoice_number']}")
    pdf.setFont("Helvetica", 10)
    pdf.drawRightString(width - 45, height - 72, f"Issued: {invoice['issued_on']}")
    pdf.drawRightString(width - 45, height - 88, f"Due: {invoice['due_date']}")

    y = height - 130
    details = [
        f"Patient: {invoice['patient_name']}",
        f"Phone: {invoice['patient_phone']}",
        f"Address: {invoice['patient_address']}",
        f"Diagnosis: {invoice['patient_diagnosis']}",
        f"Doctor Assigned: {invoice['patient_doctor']}",
    ]
    pdf.setFont("Helvetica", 11)
    for line in details:
        pdf.drawString(45, y, line)
        y -= 18

    y -= 16
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(45, y, "Description")
    pdf.drawString(320, y, "Status")
    pdf.drawRightString(width - 45, y, "Amount")
    y -= 14
    pdf.line(45, y, width - 45, y)
    y -= 20

    pdf.setFont("Helvetica", 10)
    pdf.drawString(45, y, "Clinical Services and Consultation")
    pdf.drawString(320, y, str(invoice["status"]))
    pdf.drawRightString(width - 45, y, format_currency(float(invoice["amount"])))

    y -= 32
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawRightString(width - 45, y, f"Total: {format_currency(float(invoice['amount']))}")

    pdf.setFont("Helvetica-Oblique", 9)
    pdf.drawString(
        45,
        40,
        "Auto-generated by SIMS Hospital Cloud demo. Production deployments support enterprise audit trails.",
    )
    pdf.save()
    buffer.seek(0)
    return buffer.read()


def _print_frame(invoice_html: str) -> str:
    return f"""
    <html>
      <head>
        <style>
          body {{
            font-family: Inter, Poppins, sans-serif;
            margin: 20px;
            background: #fdf9f2;
          }}
          .invoice-paper {{
            background: #fff;
            border-radius: 12px;
            padding: 24px;
            box-shadow: 0 8px 20px rgba(0,0,0,0.08);
          }}
          .invoice-header {{
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
          }}
          .invoice-table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 16px;
          }}
          .invoice-table th, .invoice-table td {{
            border-bottom: 1px solid #eee3cb;
            padding: 10px 8px;
            text-align: left;
          }}
          .invoice-total {{
            margin-top: 18px;
            text-align: right;
            font-size: 18px;
            font-weight: 700;
          }}
        </style>
      </head>
      <body>
        {invoice_html}
        <script>
          window.print();
        </script>
      </body>
    </html>
    """


def render_billing_page(context: Dict[str, str]) -> None:
    st.markdown("## Billing Module")
    st.caption(f"{context['hospital_name']} | Auto-generated invoices and PDF export")

    patients = fetch_patients()
    if not patients:
        st.info("No patient records available for billing.")
        return

    labels = [f"#{patient['id']} - {patient['name']}" for patient in patients]
    selected_label = st.selectbox("Select Patient for Billing", labels)
    selected_patient = patients[labels.index(selected_label)]

    summary_left, summary_right = st.columns(2, gap="medium")
    with summary_left:
        st.markdown(
            f"""
            <div class="insight-card">
                <h4>Billing Amount</h4>
                <p>{format_currency(float(selected_patient['billing_amount']))}</p>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with summary_right:
        st.markdown(
            f"""
            <div class="insight-card">
                <h4>Payment Status</h4>
                <p>{selected_patient['payment_status']}</p>
            </div>
            """,
            unsafe_allow_html=True,
        )

    if st.button("Auto Generate Invoice", type="primary"):
        invoice = create_invoice(int(selected_patient["id"]), context["username"])
        st.session_state.latest_invoice_id = invoice["id"]
        st.success(f"Invoice {invoice['invoice_number']} generated successfully.")

    invoice_id = st.session_state.get("latest_invoice_id")
    invoice = get_invoice(invoice_id) if invoice_id else None

    if invoice:
        st.markdown("### Invoice Preview")
        preview_html = _invoice_preview_html(invoice, context["hospital_name"])
        st.markdown(preview_html, unsafe_allow_html=True)

        download_col, print_col = st.columns(2, gap="small")
        with download_col:
            pdf_data = _build_invoice_pdf(invoice, context["hospital_name"])
            st.download_button(
                "Download Invoice as PDF",
                data=pdf_data,
                file_name=f"{invoice['invoice_number']}.pdf",
                mime="application/pdf",
                use_container_width=True,
            )
        with print_col:
            if st.button("Open Print Friendly Invoice", use_container_width=True):
                components.html(_print_frame(preview_html), height=640, scrolling=True)

    st.markdown("### Recent Invoices")
    recent = list_recent_invoices()
    if not recent:
        st.info("No invoices generated yet.")
        return
    table = pd.DataFrame(recent)
    table.columns = ["ID", "Invoice Number", "Amount", "Status", "Issued On", "Patient Name"]
    table["Amount"] = table["Amount"].apply(lambda amount: format_currency(float(amount)))
    st.dataframe(table, use_container_width=True, hide_index=True)
